In [1]:
from redshift_compiler import *

In [2]:
# calibration for tpcds
jg = joinGraph("tpcds")
jg.add_table("tpcds.store_sales2", ["ss_sold_date_sk","ss_sold_time_sk","ss_item_sk","ss_customer_sk","ss_cdemo_sk","ss_hdemo_sk","ss_addr_sk","ss_store_sk","ss_promo_sk","ss_ticket_number","ss_quantity","ss_wholesale_cost","ss_list_price","ss_sales_price","ss_ext_discount_amt","ss_ext_sales_price","ss_ext_wholesale_cost","ss_ext_list_price","ss_ext_tax","ss_coupon_amt","ss_net_paid","ss_net_paid_inc_tax","ss_net_profit"])
jg.add_table("tpcds.store",["s_store_sk","s_store_id","s_rec_start_date","s_rec_end_date","s_closed_date_sk","s_store_name","s_number_employees","s_floor_space","s_hours","s_manager","s_market_id","s_geography_class","s_market_desc","s_market_manager","s_division_id","s_division_name","s_company_id","s_company_name","s_street_number","s_street_name","s_street_type","s_suite_number","s_city","s_county","s_state","s_zip","s_country","s_gmt_offset","s_tax_precentage"])
jg.add_table("tpcds.date_dim", ["d_date_sk","d_date_id","d_date","d_month_seq","d_week_seq","d_quarter_seq","d_year","d_dow","d_moy","d_dom","d_qoy","d_fy_year","d_fy_quarter_seq","d_fy_week_seq","d_day_name","d_quarter_name","d_holiday","d_weekend","d_following_holiday","d_first_dom","d_last_dom","d_same_day_ly","d_same_day_lq","d_current_day","d_current_week","d_current_month","d_current_quarter","d_current_year"])
jg.add_table("tpcds.time_dim",["t_time_sk","t_time_id","t_time","t_hour","t_minute","t_second","t_am_pm","t_shift","t_sub_shift","t_meal_time"])
jg.add_table("tpcds.item",["i_item_sk","i_item_id","i_rec_start_date","i_rec_end_date","i_item_desc","i_current_price","i_wholesale_cost","i_brand_id","i_brand","i_class_id","i_class","i_category_id","i_category","i_manufact_id","i_manufact","i_size","i_formulation","i_color","i_units","i_container","i_manager_id","i_product_name"])
jg.add_table("tpcds.customer",["c_customer_sk","c_customer_id","c_current_cdemo_sk","c_current_hdemo_sk","c_current_addr_sk","c_first_shipto_date_sk","c_first_sales_date_sk","c_salutation","c_first_name","c_last_name","c_preferred_cust_flag","c_birth_day","c_birth_month","c_birth_year","c_birth_country","c_login","c_email_address","c_last_review_date_sk"])
jg.add_table("tpcds.customer_address",["ca_address_sk","ca_address_id","ca_street_number","ca_street_name","ca_street_type","ca_suite_number","ca_city","ca_county","ca_state","ca_zip","ca_country","ca_gmt_offset","ca_location_type"])
jg.add_table("tpcds.customer_demographics",["cd_demo_sk","cd_gender","cd_marital_status","cd_education_status","cd_purchase_estimate","cd_credit_rating","cd_dep_count","cd_dep_employed_count","cd_dep_college_count"])
jg.add_table("tpcds.household_demographics",["hd_demo_sk","hd_income_band_sk","hd_buy_potential","hd_dep_count","hd_vehicle_count"])

jg.join("tpcds.store_sales2", "tpcds.store", ["ss_store_sk"], ["s_store_sk"])
jg.join("tpcds.store_sales2", "tpcds.date_dim", ["ss_sold_date_sk"], ["d_date_sk"])
jg.join("tpcds.store_sales2", "tpcds.time_dim", ["ss_sold_time_sk"], ["t_time_sk"])
jg.join("tpcds.store_sales2", "tpcds.item", ["ss_item_sk"], ["i_item_sk"])
jg.join("tpcds.store_sales2", "tpcds.customer", ["ss_customer_sk"], ["c_customer_sk"])
jg.join("tpcds.customer", "tpcds.customer_address", ["c_current_addr_sk"], ["ca_address_sk"])
jg.join("tpcds.customer", "tpcds.customer_demographics", ["c_current_cdemo_sk"], ["cd_demo_sk"])
jg.join("tpcds.store_sales2", "tpcds.household_demographics", ["ss_hdemo_sk"], ["hd_demo_sk"])

jg.calibration("tpcds.store_sales2")

DROP materialized view IF EXISTS tpcds_m0 CASCADE;
DROP materialized view IF EXISTS tpcds_m1 CASCADE;
DROP materialized view IF EXISTS tpcds_m2 CASCADE;
DROP materialized view IF EXISTS tpcds_m3 CASCADE;
DROP materialized view IF EXISTS tpcds_m4 CASCADE;
DROP materialized view IF EXISTS tpcds_m5 CASCADE;
DROP materialized view IF EXISTS tpcds_m6 CASCADE;
DROP materialized view IF EXISTS tpcds_m7 CASCADE;
DROP materialized view IF EXISTS tpcds_m8 CASCADE;
DROP materialized view IF EXISTS tpcds_m9 CASCADE;
DROP materialized view IF EXISTS tpcds_m10 CASCADE;
DROP materialized view IF EXISTS tpcds_m11 CASCADE;
DROP materialized view IF EXISTS tpcds_m12 CASCADE;
DROP materialized view IF EXISTS tpcds_m13 CASCADE;
DROP materialized view IF EXISTS tpcds_m14 CASCADE;
DROP materialized view IF EXISTS tpcds_m15 CASCADE;
DROP materialized view IF EXISTS tpcds_m16 CASCADE;
DROP materialized view IF EXISTS tpcds_m17 CASCADE;
--sending message from tpcds.store to tpcds.store_sales2
create materialized view tpcds_m0 as
SELECT tpcds.store.s_store_sk,SUM(1)
FROM tpcds.store
GROUP BY tpcds.store.s_store_sk;
--sending message from tpcds.date_dim to tpcds.store_sales2
create materialized view tpcds_m1 as
SELECT tpcds.date_dim.d_date_sk,SUM(1)
FROM tpcds.date_dim
GROUP BY tpcds.date_dim.d_date_sk;
--sending message from tpcds.time_dim to tpcds.store_sales2
create materialized view tpcds_m2 as
SELECT tpcds.time_dim.t_time_sk,SUM(1)
FROM tpcds.time_dim
GROUP BY tpcds.time_dim.t_time_sk;
--sending message from tpcds.item to tpcds.store_sales2
create materialized view tpcds_m3 as
SELECT tpcds.item.i_item_sk,SUM(1)
FROM tpcds.item
GROUP BY tpcds.item.i_item_sk;
--sending message from tpcds.customer_address to tpcds.customer
create materialized view tpcds_m4 as
SELECT tpcds.customer_address.ca_address_sk,SUM(1)
FROM tpcds.customer_address
GROUP BY tpcds.customer_address.ca_address_sk;
--sending message from tpcds.customer_demographics to tpcds.customer
create materialized view tpcds_m5 as
SELECT tpcds.customer_demographics.cd_demo_sk,SUM(1)
FROM tpcds.customer_demographics
GROUP BY tpcds.customer_demographics.cd_demo_sk;
--sending message from tpcds.customer to tpcds.store_sales2
create materialized view tpcds_m6 as
SELECT tpcds.customer.c_customer_sk,SUM(tpcds_m4.sum*tpcds_m5.sum)
FROM tpcds_m4,tpcds_m5,tpcds.customer
WHERE tpcds_m4.ca_address_sk = tpcds.customer.c_current_addr_sk AND tpcds_m5.cd_demo_sk = tpcds.customer.c_current_cdemo_sk
GROUP BY tpcds.customer.c_customer_sk;
--sending message from tpcds.household_demographics to tpcds.store_sales2
create materialized view tpcds_m7 as
SELECT tpcds.household_demographics.hd_demo_sk,SUM(1)
FROM tpcds.household_demographics
GROUP BY tpcds.household_demographics.hd_demo_sk;
--downward message passing
--sending message from tpcds.store_sales2 to tpcds.store
create materialized view tpcds_m8 as
SELECT tpcds.store_sales2.ss_store_sk,SUM(tpcds_m1.sum*tpcds_m2.sum*tpcds_m3.sum*tpcds_m6.sum*tpcds_m7.sum)
FROM tpcds_m1,tpcds_m2,tpcds_m3,tpcds_m6,tpcds_m7,tpcds.store_sales2
WHERE tpcds_m1.d_date_sk = tpcds.store_sales2.ss_sold_date_sk AND tpcds_m2.t_time_sk = tpcds.store_sales2.ss_sold_time_sk AND tpcds_m3.i_item_sk = tpcds.store_sales2.ss_item_sk AND tpcds_m6.c_customer_sk = tpcds.store_sales2.ss_customer_sk AND tpcds_m7.hd_demo_sk = tpcds.store_sales2.ss_hdemo_sk
GROUP BY tpcds.store_sales2.ss_store_sk;
--sending message from tpcds.store_sales2 to tpcds.date_dim
create materialized view tpcds_m9 as
SELECT tpcds.store_sales2.ss_sold_date_sk,SUM(tpcds_m0.sum*tpcds_m2.sum*tpcds_m3.sum*tpcds_m6.sum*tpcds_m7.sum)
FROM tpcds_m0,tpcds_m2,tpcds_m3,tpcds_m6,tpcds_m7,tpcds.store_sales2
WHERE tpcds_m0.s_store_sk = tpcds.store_sales2.ss_store_sk AND tpcds_m2.t_time_sk = tpcds.store_sales2.ss_sold_time_sk AND tpcds_m3.i_item_sk = tpcds.store_sales2.ss_item_sk AND tpcds_m6.c_customer_sk = tpcds.store_sales2.ss_customer_sk AND tpcds_m7.hd_demo_sk = tpcds.store_sales2.ss_hdemo_sk
GROUP BY tpcds.store_sales2.ss_sold_date_sk;
--sending message from tpcds.store_sales2 to tpcds.time_dim
create materialized view tpcds_m10 as
SELECT tpcds.store_sales2.ss_sold_time_sk,SUM(tpcds_m0.sum*tpcds_m1.sum*tpcds_m3.sum*tpcds_m6.sum*tpcds_m7.sum)
FROM tpcds_m0,tpcds_m1,tpcds_m3,tpcds_m6,tpcds_m7,tpcds.store_sales2
WHERE tpcds_m0.s_store_sk = tpcds.store_sales2.ss_store_sk AND tpcds_m1.d_date_sk = tpcds.store_sales2.ss_sold_date_sk AND tpcds_m3.i_item_sk = tpcds.store_sales2.ss_item_sk AND tpcds_m6.c_customer_sk = tpcds.store_sales2.ss_customer_sk AND tpcds_m7.hd_demo_sk = tpcds.store_sales2.ss_hdemo_sk
GROUP BY tpcds.store_sales2.ss_sold_time_sk;
--sending message from tpcds.store_sales2 to tpcds.item
create materialized view tpcds_m11 as
SELECT tpcds.store_sales2.ss_item_sk,SUM(tpcds_m0.sum*tpcds_m1.sum*tpcds_m2.sum*tpcds_m6.sum*tpcds_m7.sum)
FROM tpcds_m0,tpcds_m1,tpcds_m2,tpcds_m6,tpcds_m7,tpcds.store_sales2
WHERE tpcds_m0.s_store_sk = tpcds.store_sales2.ss_store_sk AND tpcds_m1.d_date_sk = tpcds.store_sales2.ss_sold_date_sk AND tpcds_m2.t_time_sk = tpcds.store_sales2.ss_sold_time_sk AND tpcds_m6.c_customer_sk = tpcds.store_sales2.ss_customer_sk AND tpcds_m7.hd_demo_sk = tpcds.store_sales2.ss_hdemo_sk
GROUP BY tpcds.store_sales2.ss_item_sk;
--sending message from tpcds.store_sales2 to tpcds.customer
create materialized view tpcds_m12 as
SELECT tpcds.store_sales2.ss_customer_sk,SUM(tpcds_m0.sum*tpcds_m1.sum*tpcds_m2.sum*tpcds_m3.sum*tpcds_m7.sum)
FROM tpcds_m0,tpcds_m1,tpcds_m2,tpcds_m3,tpcds_m7,tpcds.store_sales2
WHERE tpcds_m0.s_store_sk = tpcds.store_sales2.ss_store_sk AND tpcds_m1.d_date_sk = tpcds.store_sales2.ss_sold_date_sk AND tpcds_m2.t_time_sk = tpcds.store_sales2.ss_sold_time_sk AND tpcds_m3.i_item_sk = tpcds.store_sales2.ss_item_sk AND tpcds_m7.hd_demo_sk = tpcds.store_sales2.ss_hdemo_sk
GROUP BY tpcds.store_sales2.ss_customer_sk;
--sending message from tpcds.customer to tpcds.customer_address
create materialized view tpcds_m13 as
SELECT tpcds.customer.c_current_addr_sk,SUM(tpcds_m12.sum*tpcds_m5.sum)
FROM tpcds_m12,tpcds_m5,tpcds.customer
WHERE tpcds_m12.ss_customer_sk = tpcds.customer.c_customer_sk AND tpcds_m5.cd_demo_sk = tpcds.customer.c_current_cdemo_sk
GROUP BY tpcds.customer.c_current_addr_sk;
--sending message from tpcds.customer to tpcds.customer_demographics
create materialized view tpcds_m14 as
SELECT tpcds.customer.c_current_cdemo_sk,SUM(tpcds_m12.sum*tpcds_m4.sum)
FROM tpcds_m12,tpcds_m4,tpcds.customer
WHERE tpcds_m12.ss_customer_sk = tpcds.customer.c_customer_sk AND tpcds_m4.ca_address_sk = tpcds.customer.c_current_addr_sk
GROUP BY tpcds.customer.c_current_cdemo_sk;
--sending message from tpcds.store_sales2 to tpcds.household_demographics
create materialized view tpcds_m15 as
SELECT tpcds.store_sales2.ss_hdemo_sk,SUM(tpcds_m0.sum*tpcds_m1.sum*tpcds_m2.sum*tpcds_m3.sum*tpcds_m6.sum)
FROM tpcds_m0,tpcds_m1,tpcds_m2,tpcds_m3,tpcds_m6,tpcds.store_sales2
WHERE tpcds_m0.s_store_sk = tpcds.store_sales2.ss_store_sk AND tpcds_m1.d_date_sk = tpcds.store_sales2.ss_sold_date_sk AND tpcds_m2.t_time_sk = tpcds.store_sales2.ss_sold_time_sk AND tpcds_m3.i_item_sk = tpcds.store_sales2.ss_item_sk AND tpcds_m6.c_customer_sk = tpcds.store_sales2.ss_customer_sk
GROUP BY tpcds.store_sales2.ss_hdemo_sk;

In [3]:
# calibration of chain schema with groupby in pivot query
jg = joinGraph("")
jg.add_table("R1", ["A", "B"])
jg.add_table("R2", ["B", "C"])
jg.add_table("R3", ["C", "D"])
jg.add_table("R4", ["D", "E"])
jg.add_table("R5", ["E", "F"])
jg.add_table("R6", ["F", "G"])
jg.add_table("R7", ["G", "H"])
jg.add_table("R8", ["H", "I"])

jg.join("R1", "R2", ["B"], ["B"])
jg.join("R2", "R3", ["C"], ["C"])
jg.join("R3", "R4", ["D"], ["D"])
jg.join("R4", "R5", ["E"], ["E"])
jg.join("R5", "R6", ["F"], ["F"])
jg.join("R6", "R7", ["G"], ["G"])
jg.join("R7", "R8", ["H"], ["H"])

jg.calibration("R8", groupby=['A','B', 'C', 'D'])

DROP materialized view IF EXISTS _m0 CASCADE;
DROP materialized view IF EXISTS _m1 CASCADE;
DROP materialized view IF EXISTS _m2 CASCADE;
DROP materialized view IF EXISTS _m3 CASCADE;
DROP materialized view IF EXISTS _m4 CASCADE;
DROP materialized view IF EXISTS _m5 CASCADE;
DROP materialized view IF EXISTS _m6 CASCADE;
DROP materialized view IF EXISTS _m7 CASCADE;
DROP materialized view IF EXISTS _m8 CASCADE;
DROP materialized view IF EXISTS _m9 CASCADE;
DROP materialized view IF EXISTS _m10 CASCADE;
DROP materialized view IF EXISTS _m11 CASCADE;
DROP materialized view IF EXISTS _m12 CASCADE;
DROP materialized view IF EXISTS _m13 CASCADE;
DROP materialized view IF EXISTS _m14 CASCADE;
DROP materialized view IF EXISTS _m15 CASCADE;
--sending message from R1 to R2
create materialized view _m0 as
SELECT R1.B,R1.A,SUM(1)
FROM R1
GROUP BY R1.B,R1.A;
--sending message from R2 to R3
create materialized view _m1 as
SELECT R2.C,_m0.A,R2.B,SUM(_m0.sum)
FROM _m0,R2
WHERE _m0.B = R2.B
GROUP BY R2.C,_m0.A,R2.B;
--sending message from R3 to R4
create materialized view _m2 as
SELECT R3.D,_m1.A,_m1.B,R3.C,SUM(_m1.sum)
FROM _m1,R3
WHERE _m1.C = R3.C
GROUP BY R3.D,_m1.A,_m1.B,R3.C;
--sending message from R4 to R5
create materialized view _m3 as
SELECT R4.E,_m2.A,_m2.B,_m2.C,R4.D,SUM(_m2.sum)
FROM _m2,R4
WHERE _m2.D = R4.D
GROUP BY R4.E,_m2.A,_m2.B,_m2.C,R4.D;
--sending message from R5 to R6
create materialized view _m4 as
SELECT R5.F,_m3.A,_m3.B,_m3.C,_m3.D,SUM(_m3.sum)
FROM _m3,R5
WHERE _m3.E = R5.E
GROUP BY R5.F,_m3.A,_m3.B,_m3.C,_m3.D;
--sending message from R6 to R7
create materialized view _m5 as
SELECT R6.G,_m4.A,_m4.B,_m4.C,_m4.D,SUM(_m4.sum)
FROM _m4,R6
WHERE _m4.F = R6.F
GROUP BY R6.G,_m4.A,_m4.B,_m4.C,_m4.D;
--sending message from R7 to R8
create materialized view _m6 as
SELECT R7.H,_m5.A,_m5.B,_m5.C,_m5.D,SUM(_m5.sum)
FROM _m5,R7
WHERE _m5.G = R7.G
GROUP BY R7.H,_m5.A,_m5.B,_m5.C,_m5.D;
--downward message passing
--sending message from R8 to R7
create materialized view _m7 as
SELECT R8.H,SUM(1)
FROM R8
GROUP BY R8.H;
--sending message from R7 to R6
create materialized view _m8 as
SELECT R7.G,SUM(_m7.sum)
FROM _m7,R7
WHERE _m7.H = R7.H
GROUP BY R7.G;
--sending message from R6 to R5
create materialized view _m9 as
SELECT R6.F,SUM(_m8.sum)
FROM _m8,R6
WHERE _m8.G = R6.G
GROUP BY R6.F;
--sending message from R5 to R4
create materialized view _m10 as
SELECT R5.E,SUM(_m9.sum)
FROM _m9,R5
WHERE _m9.F = R5.F
GROUP BY R5.E;
--sending message from R4 to R3
create materialized view _m11 as
SELECT R4.D,SUM(_m10.sum)
FROM _m10,R4
WHERE _m10.E = R4.E
GROUP BY R4.D;
--sending message from R3 to R2
create materialized view _m12 as
SELECT R3.C,R3.D,SUM(_m11.sum)
FROM _m11,R3
WHERE _m11.D = R3.D
GROUP BY R3.C,R3.D;
--sending message from R2 to R1
create materialized view _m13 as
SELECT R2.B,R2.C,_m12.D,SUM(_m12.sum)
FROM _m12,R2
WHERE _m12.C = R2.C
GROUP BY R2.B,R2.C,_m12.D;